<!DOCTYPE collection [
  <!ELEMENT collection (text+,stats?)>
  <!ELEMENT text (rohtext)>
  <!ATTLIST text person CDATA #REQUIRED>
  <!ATTLIST text titel CDATA #REQUIRED>
  <!ATTLIST text datum CDATA #REQUIRED>
  <!ATTLIST text ort CDATA #REQUIRED>
  <!ATTLIST text untertitel CDATA #REQUIRED>
  <!ATTLIST text url CDATA #REQUIRED>
  <!ATTLIST text anrede CDATA #REQUIRED>
  <!ELEMENT rohtext (#PCDATA)>
]>


<collection>
<text person="Norbert Lammert" titel="Deutscher Bundestag - Rede des Bundestagspräsidenten Dr. Norbert Lammert anlässlich der Verleihung des Internationalen Brückepreises der Europastadt Görlitz/Zgorzelec an den estnischen Komponisten Arvo Pärt am 9. November 2007 in Görlitz" datum="" ort=""  untertitel="" url="https://www.bundestag.de/parlament/praesidium/reden/2007/018/246474" anrede="">
<rohtext>
Verehrter Herr Pärt,sehr geehrte Frau Pärt,sehr geehrte hohe Repräsentanten Polens, Estlands und Deutschlands,meine Damen und Herren.
Gäbe es im Jahreskalender so etwas wie einen &quot;deutschen Tag&quot;, es wäre ganz sicher der 9. November. Kein anderes Datum markiert in vergleichbarer Weise herausragende Ereignisse, Höhepunkte und Tiefpunkte der deutschen Geschichte. Von der Ausrufung der Republik 1918 nach dem I. Weltkrieg über die staatlich organisierten Judenprogrome 1938 bis zum Fall der Mauer 1989. Es gibt kein geeigneteres Datum für die Verleihung eines Internationalen Brückepreises und es gibt wohl auch keinen geeigneteren Ort dafür als diesen.
Brücken spielen in der Geschichte der beinahe tausendjährigen Europastadt Görlitz/Zgorzelec seit je her eine große Rolle. Sieben Neißebrücken verbanden den Westteil mit dem Ostteil ein und derselben Stadt. Sie wurde im Mai 1945 gesprengt und nicht oder nur teilweise wieder aufgebaut, nachdem die Stadt im Ergebnis des II. Weltkriegs in einen deutschen und einen polnischen Teil getrennt und geteilt wurden.
Seit der großen politischen Wende der späten 80er und frühen 90er Jahre wurden dann nach und nach viele neue, zunächst menschliche Brücken errichtet und seit Oktober 2004 verbindet auch die wieder aufgebaute Altstadtbrücke an historischer Stelle nach fast 60-jähriger Unterbrechung wieder die beiden Neißeufer.
Die Stadt hat sich verändert, weil Europa sich verändert hat. Als in Berlin die Mauer fiel, am 9. November 1989, war der deutsche Regierungschef Helmut Kohl in Polen zu einem offiziellen Besuch beim ersten frei gewählten polnischen Ministerpräsidenten seit 1945, Tadeusz Mazowiecki. Er musste aufgrund der buchstäblich unglaublichen Ereignisse in Berlin seinen Besuch unterbrechen und hat seinen Besuch dann nach zwei Tagen in Polen fortgesetzt.
Die beiden Regierungschefs waren sich damals sehr bewusst, dass die einmalige historische Situation nach einer besonderen politischen Geste verlangte. Spontan sind die deutsche und die polnische Delegation nach Kreisau gereist. Auf dem dort gelegenen, zum damaligen Zeitpunkt völlig zerfallenen Gut der Familie Moltke, auf dem seinerzeit die Widerstandsgruppe des Kreisauer Kreises zusammengekommen war, haben sie gemeinsam eine katholische Messe besucht, die ein Signal der Verständigung und Versöhnung zwischen beiden Ländern sein sollte.
Den 18. Jahrestag des Falls der Berliner Mauer heute am 9. November 2007 habe ich ganz in der Früh weit nach Mitternacht mit Musik von Arvo Pärt begonnen. Mit zwei Werken, von denen ich meine, dass sie zu diesem Datum und seiner Ambivalenz in einer besonderen Weise passen. &quot;De Profundis&quot;, den berühmten Klageruf aus den Psalmen und seiner &quot;Berliner Messe&quot;, die er nicht irgendwann, sondern 1989/90 geschrieben hat. Ich habe die Musik von Arvo Pärt nicht nur deshalb aufgelegt, weil ich wusste, dass ich den heutigen Abend mit ihm würde verbringen dürfen, sondern weil seine Biografie, seine Musik und sein Lebenswerk in ganz besonderer Weise für die neuen Brücken stehen, die Europa braucht und glücklicherweise wieder oder erstmals hat: physische und mentale Brücken, politische und kulturelle, ökonomische und wissenschaftliche.
In dieser, erst im zeitlichen Abstand wirklich begreifbaren Zeit der großen Wende, als Polen nach vielen bitteren Jahrzehnten seine Freiheit fand und Deutschland seine Einheit wieder erhielt, als dieser über Jahrzehnte geteilte Kontinent seine Zusammengehörigkeit wieder herstellte, wurde immer deutlicher, dass das eine ohne das andere nicht zu haben war. Die Deutsche Einheit nicht ohne die Wiederherstellung der Einheit Europas und die Einheit Europas nicht ohne die Wiederherstellung der Einheit Deutschlands. Damals wurde ein Konzept Wirklichkeit, von dem die Gründerväter und -mütter dieses Gedankens sich schwerlich zugetraut hätten, dieses Ergebnis verbindlich zuzusagen und schon gar nicht Termine dafür anzugeben.
Im März dieses Jahres haben wir das 50. Jubiläum der Römischen Verträge in Berlin gefeiert und damit an ein Vertragswerk erinnert, mit dem zunächst sechs westeuropäische Staaten eine Wirtschaftsgemeinschaft begründet haben, ihre ökonomischen Interessen in einer neuen Weise miteinander verbunden und ihre Märkte nicht sofort, aber von der erklärten vertraglichen Absicht her zunehmend füreinander geöffnet haben. Damals hätte niemand sich vorstellen können, dass diese Gemeinschaft ihren 50. Geburtstag nicht als Wirtschaftsgemeinschaft, sondern als politische Union von inzwischen 27 Staaten aus Westeuropa, aus Mittel- und aus Osteuropa würde begehen können.
Wenn solche Jubiläen über den statistischen Reiz einer runden Jahreszahl hinaus überhaupt Sinn haben, dann sind sie besonders gute und im Alltag nicht allzu häufige Gelegenheiten zur Besinnung über das, was da stattgefunden hat und zur Selbstverständigung über das, was man sich für die Zukunft gemeinsam vornimmt.
Und gerade das neue Europa, das mit den 27 Mitgliedsstaaten ganz gewiss noch nicht am Ende seiner Entwicklung angekommen ist, hat besonderen Grund darüber nachzudenken, als was es sich eigentlich versteht. Als einen politischen Club, als einen großen gemeinsamen Markt oder als eine gemeinsame Idee. Ich bin fest davon überzeugt, dass die einzig identitätsstiftende Perspektive das Verständnis Europas als Idee ist. Das nimmt der politischen Organisation der Zusammenarbeit dieser Staaten und auch ihrer ökonomischen Kooperation nichts von ihrer Zweckmäßigkeit, aber als Grundlage der Identifikation von Menschen mit einer Gemeinschaft reicht weder der Charme der Brüsseler Bürokratie noch der Reiz großer gemeinsamer Märkte und damit verbundener wirtschaftlicher Interessen.
Der Kern des Selbstverständnisses Europas ist eine große gemeinsame Idee. Die Idee vom Menschen als einer für sich selbst verantwortlichen Persönlichkeit mit einer nicht antastbaren Würde - eine gedankliche Figur, von der sich übrigens mühelos erkennen lässt, dass sie die durch die Aufklärung erfolgte Säkularisierung der christlichen Überzeugung von der Gottesebenbildlichkeit des Menschen darstellt - und die daraus hergeleiteten Überzeugungen vom unaufgebbaren Anspruch auf Freiheit, auf freie Entfaltung der Persönlichkeit, auf Mitwirkung, auf Demokratie, auf Rechtstaat, auf Toleranz, auf soziale Gerechtigkeit. Wenn überhaupt irgendetwas den inneren Zusammenhalt dieses Europas ausmacht, dann ist es diese Idee. Und der Kern dieser Idee ist Kultur. Nicht Politik hält eine Gemeinschaft zusammen, sondern Kultur: Überzeugungen, Prinzipien, Orientierungen, die man für richtig und unaufgebbar hält. Und deswegen ist gerade ein Jubiläumsjahr der Europäischen Gemeinschaft eine besonders gute Gelegenheit, nicht nur mit Respekt für ein halbes Jahrhundert, das hinter uns liegt, mit Stolz auf die Errungenschaften zurückzublicken, die schon gar im Lichte einer in aller Regel zuvor völlig anders verlaufenen europäischen Geschichte außergewöhnlich eindrucksvoll sind, sondern sich über das zu verständigen, was man eigentlich für die weitere Wegstrecke gemeinsam vor hat.
Ich verstehe den Internationalen Brückepreis als einen Beitrag zu genau dieser Selbstverständigung und als den nicht nur gut gemeinten, sondern notwendigen Beitrag, regelmäßig Persönlichkeiten auszuzeichnen, die zu genau dieser Selbstverständigung Europas über sich selbst einen ganz persönlichen Beitrag geleistet haben, und die im Sinne des Namens dieses Preises &quot;Brücken&quot; gebaut haben: zwischen der Vergangenheit und der Gegenwart, aus der Gegenwart in die Zukunft, zwischen dem Osten und dem Westen, zwischen dieser und jener großen kulturellen Tradition dieses gemeinsamen Kontinents.
Arvo Pärt ist ein solcher Brückenbauer. Es ist heute Abend weder nötig noch möglich, den Rang des Komponisten Arvo Pärt für die zeitgenössische Musik zu würdigen, aber niemand muss Sorge haben, dass das nicht ohnehin erfolgt, wenn es nicht endlich heute Abend vorgetragen würde. Seinen Platz in der Musikgeschichte des ausgehenden 20. und beginnenden 21. Jahrhunderts ist längst unangefochten.
Ich will in meiner Laudatio ein paar Hinweise darauf geben, warum und wie ausgerechnet mit musikalischen Mitteln ein Beitrag zu dieser kulturellen Selbstverständigung, zur Stabilisierung oder Wiedererrichtung von Brücken in Europa geleistet werden kann. Und ich will damit unterstreichen, was die Gesellschaft zur Verleihung des Internationalen Brückepreises für ihre Entscheidung der Preisvergabe an Arvo Pärt selber vorgetragen hat: &quot;Arvo Pärt hat mit musikalischen Mitteln dazu beigetragen, die spirituell prägenden Kräfte Europas aufeinander zuzuführen. In seinem Schaffen treffen sich Traditionen aus dem östlich-orthodoxen, dem römisch-katholischen und dem protestantischen Europa und bereichern sich wechselseitig. Es gelang ihm, eine Brücke zwischen Ästhetik, Ethik und Spiritualität zu schlagen und Elemente der Musiksprache des Ostens in die Konzertsäle des Westens einzubringen und einem breiten Publikum zugänglich zu machen.&quot;
Meine Damen und Herren, schon die biografischen Daten Arvo Pärts sind ein Beleg für die Notwendigkeiten des Brückenbauens in Europa, insbesondere in der Zeit, in der die Teilung dieses Kontinents manifest war. Der Oberbürgermeister hat in seiner Begrüßung bereits auf einige Stationen des Lebens und auch des künstlerischen Wirkens von Arvo Pärt hingewiesen. Ich darf vielleicht noch einmal ergänzen, wie sehr sich auch im persönlichen Lebensschicksal die Folgen der ideologischen Trennung und des drohenden kulturellen Bruchs dieses Kontinents bemerkbar gemacht haben.
Sein 1968 komponiertes &quot;Credo&quot; war ein so überragender musikalischer Erfolg, dass er schon bei der Uraufführung sofort wiederholt werden musste, und zugleich eine so riesige politische Provokation, dass es anschließend prompt verboten wurde. Auf der Suche nach seiner eigenen Stimme in der kulturellen Tradition dieses Kontinents und der Auseinandersetzung mit anderen zeitgenössischen Komponisten hat Arvo Pärt sich damals für beinahe acht Jahre aus jeder aktiven Kompositionsarbeit zurückgezogen. Er hat später einmal gesagt, das war die Zeit, in der ich &quot;wieder gehen lernen&quot; musste. Pärt hat mit seiner intensiven Beschäftigung mit der kulturellen Tradition jahrhundertelang zurückliegenden Formen und Sprachen der musikalischen Tradition dieses Kontinents eine neue Begründung für seine eigene kompositorische Handschrift gesucht und gefunden.
Nach seiner Ausreise aus Estland zunächst nach Wien und dann nach Berlin Anfang der 80er Jahre wurden seine Werke zunehmend auch in Europa und in den USA bekannt. Von einem seiner bedeutenden Werke aus den späten 70er Jahren &quot;Tabula rasa&quot; hat ein amerikanisches Fachmagazin nach der Aufführung dieses Werkes in den USA geschrieben, Arvo Pärts Musik müsse als der Versuch verstanden werden &quot;das 20. Jahrhundert mit dem 15. Jahrhundert musikalisch zu verbinden und alles dazwischen zu ignorieren&quot;. Nun glaube ich nicht, dass das geht. Und ich vermute, dass er das auch nie vorhatte.
Das, was stattgefunden hat, kann man nicht ignorieren. Man kann es verdrängen, was meistens nicht viel hilft, man kann es mehr oder weniger vollständig verarbeiten, man kann sich um Neuanfänge bemühen, aber nie kann man mit Aussicht auf Erfolg so tun, als hätte es nicht stattgefunden. Das geht in individuellen Biografien nicht, es geht in sozialen Gemeinschaften nicht und es geht in Staaten und Nationen auch nicht. Aber die Bedeutung des künstlerischen Schaffens von Arvo Pärt besteht eben nicht in der Kunst des Ignorierens, sondern in dem Genie, Brücken zu schlagen, zwischen dem Ausdruckbedürfnis unserer Zeit und den Ausdrucksformen und -möglichkeiten von Generationen, die Jahrhunderte vor uns, hier, auf dem gleichen Kontinent gelebt haben.
Es ist vorhin mit Recht hervorgehoben worden, dass die Auseinandersetzung mit religiösen Themen einen, wenn nicht den zentralen Stellenwert im musikalischen Schaffen von Arvo Pärt darstellen. Dafür ließen sich viele Beispiele nennen. Ich will nur zwei wenigstens als Titel nennen, seine bedeutende &quot;Johannes-Passion&quot; Anfang der 80er Jahre und die Vertonung von Gebeten des heiligen Johannes Chrysostomus, einen auf englische Texte vertontes Werk, eine &quot;Litanei&quot;, für deren Komposition er sich übrigens auf den Berg Sinai zurückgezogen hat, um die Inspirationen authentisch für sich zu gewinnen, die er für diese Arbeit zu brauchen meinte. Das letzte Werk, das ich beispielhaft für den Brückenbauer Arvo Pärt nennen will, ist das als Auftragswerk der Berliner Festwochen 2000 entstandene Orchesterwerk &quot;Orient &amp;amp; Occident&quot;. Der Brückenschlag zwischen den ganz unterschiedlichen kulturellen Traditionen zweier jeweils bedeutender Kulturkreise.
Meine Damen und Herren, Arvo Pärt schuf in der dramatischen Epoche des Umbruchs Europas, die den eisernen Vorhang bei Seite schob und ein freies, zusammenwachsendes Europa Wirklichkeit werden ließ, eine Musik, die eine stolze musikalische Tradition für das im Westen bisweilen in Vergessenheit geratene und das im Osten über Jahrzehnte inkriminierte christliche Erbe Europas wieder freilegt und fortführt. Arvo Pärt genießt weltweite Geltung, obwohl oder vielleicht gerade weil er manche irritierende Unverständlichkeiten gegenwärtiger Kompositionsweisen, die gelegentlich auch mit dogmatischem Anspruch an die Zuhörer herantreten, als sei es die einzige Möglichkeit heute Musik zu schreiben, souverän hinter sich gelassen hat.
Seine Musik will die alten Werte religiöser Musikerfahrung für die Jetztzeit wieder hörbar machen. Er gibt dem Erinnern und dem Wiederentdecken des kulturellen Erbes Europas eine musikalische Form, in der sich das zusammenwachsende Europa auf eindrucksvolle Weise seines Erbes versichert. Mit seinem musikalischen Schaffen gelang und gelingt ihm der Brückenschlag zwischen den geistigen Traditionen des östlich-orthodoxen und dem römisch-katholischen und dem protestantischen Europa für das europäische Publikum von heute.
So etwas, meine Damen und Herren, ließe sich als Programm gar nicht formulieren. Es würde zu Recht für aussichtslos gehalten. Arvo Pärt ist einer der Glücksfälle in der europäischen Musikgeschichte, denen ein solcher Brückenschlag gelungen ist. Nach Victor Hugo drückt Musik das aus, &quot;was nicht gesagt werden kann und worüber es unmöglich ist, zu schweigen&quot;. Dazu passt wunderschön eine Beschreibung der Musik Arvo Pärts, die ich auf dem Cover einer der zahlreichen CD&amp;apos;s gefunden habe, die ich von meiner Musik im Schrank stehen habe. Da wird Pärts Musik beschrieben, als &quot;the most beautiful sound next to silence&quot;. Der schönste denkbare Klang nahe der Stille.
Die Musik von Arvo Pärt ist nicht ornamental, sondern elementar. Sie ist nicht bombastisch, sondern schlicht. Sie ist eher minimalistisch als aufwändig. Sie erreicht mit minimalem Aufwand ihre maximale Wirkung. Auch deshalb, weil sie sich nicht am Möglichen orientiert, sondern am Notwendigen.
Das wäre, meine Damen und Herren, kein übles Programm für die Europäische Gemeinschaft für die nächsten 50 Jahre. Nicht möglichst viel Verzierung, sondern Konzentration auf das Wesentliche. Nicht so bombastisch wie möglich, sondern so schlicht wie möglich und nötig, nicht aufwändig, sondern mit der Souveränität, sich auf das Wesentliche zu konzentrieren.
Ich gratuliere Ihnen, Herr Pärt, von Herzen zu dieser Auszeichnung und ich schließe in diese Gratulation meinen Respekt vor der Gesellschaft ein, die mit außerordentlicher Klugheit in diesem Jahr einen besonders bemerkenswerten Preisträger gefunden hat.
Herzlichen Glückwunsch!
Ausdruck aus dem Internet-Angebot des Deutschen Bundestages
https://www.bundestag.de/de/parlament/praesidium/reden/2007/018/246474
Stand: 25.09.2017
</rohtext>
</text>

<text person="Norbert Lammert" titel="Deutscher Bundestag - Rede zum Tag des Gedenkens an die Opfer des Nationalsozialismus" datum="" ort=""  untertitel="" url="https://www.bundestag.de/parlament/praesidium/reden/2014/001/261296" anrede="">
<rohtext>
Dmitrij SchostakowitschStreichquartett Nr. 8 c-moll, op. 1101. Satz Largo
Präsident Prof. Dr. Norbert Lammert:
Sehr geehrter Herr Bundespräsident!Frau Bundeskanzlerin!Herr Präsident des Bundesrates!Herr Präsident des Bundesverfassungsgerichts!Liebe Kolleginnen und Kollegen!Exzellenzen!Verehrte Gäste!
Heute vor 70 Jahren, am 27. Januar 1944, endete die Belagerung Leningrads durch die deutsche Wehrmacht - nach fast 900 Tagen. Damals war das Sterben in der eingeschlossenen Stadt längst zu einer grausamen Alltäglichkeit geworden, die jeden Maßstab sprengte. Mindestens 800 000 Menschen, wahrscheinlich mehr als 1 Million, sind während der dreijährigen Blockade in Leningrad zu Tode gekommen, durch Luftangriffe und Artilleriebeschuss, durch Krankheiten und Kälte - die allermeisten sind verhungert.
Ihr Tod war von den Verantwortlichen des deutschen Vernichtungskrieges im Osten einkalkuliert. Leningrad sollte nicht erobert, sondern als Wiege des sogenannten &quot;jüdischen Bolschewismus&quot; vernichtet werden. Eine Anweisung an die militärische Führung vor Ort führte erläuternd aus:
Ein Interesse an der Erhaltung auch nur eines Teiles dieser großstädtischen Bevölkerung besteht in diesem Existenzkrieg unsererseits nicht.
Daniil Granin haben die Geschehnisse in dem fast vollständig von der Außenwelt abgeriegelten Leningrad persönlich und als Schriftsteller bis heute nicht losgelassen. Er selbst hat als Soldat an der Leningrader Front gekämpft. Das ganze Ausmaß der menschlichen Katastrophe hat sich jedoch auch ihm erst viele Jahre später bei der Arbeit an seinem dokumentarischen Buch über die Blockade offenbart. Ich danke Ihnen, sehr geehrter Herr Granin, dass Sie in Ihrem hohen Alter heute zu uns gekommen sind und am Tage des Gedenkens an die Opfer des Nationalsozialismus im Deutschen Bundestag zu uns sprechen werden.
(Beifall)
Am 27. Januar 1945 wurde das Konzentrations- und Vernichtungslager Auschwitz-Birkenau durch die Rote Armee befreit - zufällig auf den Tag genau ein Jahr nach Ende der Leningrader Blockade. Kein Zufall ist dagegen der Zusammenhang zwischen Auschwitz und Leningrad, zwischen dem Völkermord an den europäischen Juden und dem mörderischen Raub- und Vernichtungsfeldzug im Osten Europas: Sie wurzelten in der menschenverachtenden nationalsozialistischen Rassenideologie.
Meine Damen und Herren, wir gedenken heute aller Menschen, denen während der nationalsozialistischen Gewaltherrschaft und des von Deutschland ausgegangenen Angriffskrieges ihre Rechte, ihr Besitz, ihre Heimat, ihr Leben, ihre Würde entrissen wurden: der Juden, der Sinti und Roma, der Kranken und Menschen mit Behinderungen, der politisch Verfolgten, der Homosexuellen, der Zwangsarbeiterinnen und Zwangsarbeiter, der Opfer der Kindertransporte, der Kriegsgefangenen, der zu &quot;Untermenschen&quot; degradierten slawischen Völker - all jener, die in Auschwitz, Treblinka, Belzec und in den anderen Vernichtungslagern ermordet wurden, die erschossen, vergast, erschlagen, verbrannt, durch Zwangsarbeit vernichtet wurden, die verhungert sind. Wir gedenken auch jener, die verfolgt, drangsaliert, getötet wurden, weil sie Widerstand leisteten oder weil sie anderen Schutz und Hilfe gewährten. Allen heute hier im Bundestag anwesenden Zeitzeugen gilt unser besonderer Gruß und Respekt.
Wir wissen um die Abermillionen Toten. Ihnen sind wir es schuldig, uns jenseits der ebenso unglaublichen wie abstrakten Zahlen bewusst zu machen, dass damals - um mit der russischen Schriftstellerin und Blockadeüberlebenden Lidia Ginsburg zu sprechen - &quot;millionenfach ein Mensch&quot; zugrunde gegangen ist.
Wir wissen auch um die Täter. &quot;Auch-Menschen&quot; hat sie der jüdisch-sowjetische Kriegsreporter Wassili Grossmann in seinem Augenzeugenbericht über Treblinka genannt. Und bis heute treibt uns - trotz allen Wissens um die historischen Zusammenhänge, trotz mancher klugen Analysen - die Frage um: Wie ist eine solche Entmenschlichung möglich geworden?
Mit dem Angriff auf die Sowjetunion erreichte die nationalsozialistische Vernichtungspolitik eine neue Dimension: In den besetzten sowjetischen Gebieten nahm der umfassende systematische Massenmord seinen Lauf. Mit dem völkerrechtswidrigen sogenannten &quot;Barbarossa-Erlass&quot; hatte Hitler auch Zivilisten praktisch für vogelfrei erklärt; sie wurden als vorgebliche oder tatsächliche Partisanen und im Zuge von sogenannten &quot;Vergeltungsmaßnahmen&quot; getötet.
Von den fast 3 Millionen osteuropäischen Juden, die mit dem Krieg gegen die Sowjetunion unter deutsche Herrschaft kamen, hat nur ein Bruchteil überlebt. Ein großer Teil dieser Opfer des Holocaust war bereits vernichtet, vornehmlich durch Erschießen, als im Verlauf des Jahres 1942 die fabrikmäßige Ermordung in den Vernichtungslagern anlief. Der Treibstoff für die Tötungsmaschinerie in Auschwitz, das Giftgas Zyklon B, war vorab an sowjetischen Kriegsgefangenen - man muss es so sagen - getestet worden.
Der rassenideologische Raub- und Vernichtungskrieg, dessen erklärter Zweck die &quot;Dezimierung der slawischen Bevölkerung um 30 Millionen&quot; war, bediente sich einer weiteren Waffe: des Hungers. Sie erwies sich dort am brutalsten, wo es kein Entkommen gab: im eingeschlossenen Leningrad und in den Kriegsgefangenenlagern. Mehr als die Hälfte aller sowjetischen Kriegsgefangenen, über 3 Millionen Menschen, sind in deutschem Gewahrsam elendig zugrunde gegangen.
Die menschlichen Tragödien, die sich in der belagerten Millionenmetropole abspielten, sind uns heute völlig unvorstellbar. Lange Zeit waren sie, zumindest im Westen Deutschlands, auch wenig bekannt. Die Erinnerung an den Russlandfeldzug war in der jungen Bundesrepublik von der Tragödie bei Stalingrad in ihrer besonderen deutschen Wahrnehmung dominiert; die Belagerung Leningrads und die dem Hunger preisgegebenen Zivilisten fanden im Mythos einer vermeintlich &quot;sauberen Wehrmacht&quot; keinen Platz. In der DDR, die den Antifaschismus zur Staatsdoktrin erhoben hatte, war hingegen die sowjetische Sichtweise prägend: Die Blockade Leningrads demonstrierte demnach die herausragende Opferbereitschaft seiner Einwohner und galt als Symbol für den heldenhaften sowjetischen Sieg gegen den Faschismus. Die leidvolle Wirklichkeit des Lebens in der abgeriegelten, hungernden Metropole im brutalen Kampf zwischen zwei totalitären Regimen stand auch hier nicht im Vordergrund.
Unter den Eingeschlossenen war - bis zu seiner Evakuierung - der schon damals weltberühmte Komponist Dmitrij Schostakowitsch, der später mit Blick auf seine musikalischen Werke einmal von &quot;Grabdenkmälern&quot; gesprochen hat. Für sein Streichquartett Nr. 8, das uns durch diese Gedenkstunde begleitet, gilt das insbesondere. Unter dem Eindruck des zerstörten Dresden geschrieben und offiziell den Opfern des Faschismus und des Krieges zum Gedenken gewidmet, reflektiert dieses wohl persönlichste Werk Schostakowitschs auch das eigene Erleben von Verfolgung, Krieg, Drangsalierung - die eigene von Tragik und Widersprüchen geprägte Geschichte eines russischen Künstlers, dessen Leidenszeit mit dem siegreichen &quot;Großen Vaterländischen Krieg&quot; keineswegs beendet war.
Meine Damen und Herren, es gehört zu den großen Verdiensten Daniil Granins und seines Schriftstellerkollegen Ales Adamowitsch, dass sie den Bewohnern des belagerten Leningrad jenseits der offiziellen sowjetischen Geschichtsschreibung eine Stimme gegeben haben. Ihr zweibändiges Blockadebuch konnte Ende der 1970er-, Anfang der 1980er-Jahre nur zensiert erscheinen, zu viel zeigte es von den menschlichen Abgründen in diesen 900 Tagen, über die das sowjetische Regime Schweigen bewahren wollte. In den gesammelten Erzählungen und Tagebüchern offenbart sich, was der Hunger den Menschen antut: die körperlichen und seelischen Qualen, die zerstörten Beziehungen, die Grausamkeit, der Verlust der Menschlichkeit. Es zeigt aber auch, wie Menschen selbst in größter existenzieller Not darum kämpfen, ihre Hoffnung und ihre Würde zu bewahren.
Sehr geehrter Herr Granin, Sie haben es damals ausdrücklich als eine Pflicht verstanden, für die Nachgeborenen aufzuzeichnen, was tatsächlich gewesen ist, und die junge Generation mittelbar zu Zeugen zu machen - eine Aufgabe, die sich heute nicht weniger stellt und die zu erfüllen mit jedem Jahr schwieriger wird.
Umso mehr freue ich mich, dass wieder 80 junge Menschen derEinladung des Deutschen Bundestages zu einer internationalen Jugendbegegnung gefolgt sind und sich gemeinsam mit einem der dunkelsten Kapitel in der europäischen Geschichte auseinandergesetzt haben. Sie haben in den vergangenen Tagen Orte des Gedenkens in Sankt Petersburg besucht, mit Wissenschaftlern und Zeitzeugen diskutiert, sich ein Bild vom Schicksal jüdischer Einwohner, von Zwangsarbeitern, Kriegsgefangenen, von Behinderten und psychisch Kranken in der besetzten Sowjetunion gemacht, stalinistische Repressionen während der Leningrader Blockade und den Umgang mit der Erinnerung an diese fast 900 Tage thematisiert. Seien Sie hier im Deutschen Bundestag herzlich willkommen!
(Beifall)
Wenn heute junge Deutsche mit jungen Russen, Belarussen und Ukrainern, mit Polen, Franzosen, Israelis und jungen Menschen aus anderen Ländern zusammenkommen, um zu erfahren, zu verstehen und zu erinnern, steht dahinter auch die Hoffnung, dass über die jeweils unterschiedliche nationale Erinnerung hinweg Brücken im Sinne eines gemeinsamen Gedächtnisses geschlagen werden können.
Ein Vierteljahrhundert nach der friedlichen Revolution in der DDR und dem Zusammenbruch der kommunistischen Diktaturen in Ost- und Mitteleuropa, der den Weg zu einer &quot;Gesamt&quot;-Europäischen Union bereitete, 75 Jahre nach dem deutschen Angriff auf Polen und ein Jahrhundert nach dem Beginn des Ersten Weltkrieges, dieser &quot;Urkatastrophe des 20. Jahrhunderts&quot;, stellt sich die Frage: Kann es eine europäische Erzählung vom blutigsten Jahrhundert in der europäischen Geschichte geben, eine miteinander geteilte Erinnerung, die unterschiedliche Erfahrungen nicht relativiert, nicht nivelliert, die Verantwortung nicht verdrängt, die keine wechselseitigen Rechnungen aufmacht, weil diese weder dem Leid der einzelnen Opfer noch der Schuld der Täter gerecht werden können?
Die Verantwortung, die wir Deutsche tragen, bleibt: Unsere Geschichte trägt uns eine besondere Verpflichtung auf, gegen jede Form von Ausgrenzung und Fremdenfeindlichkeit, gegen Heilsversprechen und kollektive Schuldzuweisungen vorzugehen. Nie wieder dürfen Staat und Gesellschaft zulassen, dass Menschen wegen ihrer Herkunft, ihrer Religion, ihrer politischen Einstellung, ihrer sexuellen Orientierung, wegen ihrer Andersartigkeitzum Feindbild einer schweigenden Mehrheit gemacht, verachtet, gedemütigt oder bedroht werden.
(Beifall)
Die von Fremdenhass getriebenen Morde an Bürgern türkischer und griechischer Herkunft, von rassistischen Parolen begleitete Proteste gegen Flüchtlingsheime, jede antisemitische Straftat - jede! -
(Beifall)
fordern unsere rechtsstaatliche, politische und zivilgesellschaftliche Gegenwehr als Demokraten heraus.
(Beifall)
In Deutschland jedenfalls ist Intoleranz nicht mehr tolerierbar.
(Beifall)
Meine Damen und Herren, die Geschichte lehrt uns die Unbedingtheit der Würde des Menschen - jedes einzelnen Menschen - und das Wissen um ihre Gefährdung. Völkermord bleibt möglich: in Afrika, wie in Ruanda vor 20 Jahren, wo Hunderttausende Menschen, geschätzte drei Viertel der ethnischen Minderheit der Tutsi, ermordet wurden, und auch in Europa, wie wir seit Srebrenica wissen. Im Bewusstsein zu halten, dass die Menschheit ihre größten Verirrungen und Verbrechen keineswegs ein für allemal hinter sich hat, bleibt unsere gemeinsame Verantwortung.
Sehr geehrter Herr Granin, Sie haben in Bezug auf die Deutschen von sich einmal gesagt, dass Sie &quot;vom Hass zum Verständnis und zur Freundschaft&quot; einen langen Weg zurückgelegt haben, der Sie weit mehr Jahre gekostet habe als der Krieg. Ich bin dankbar, dass Sie diesen Weg auf sich genommen haben und heute bei uns sind. Und ich danke allen, die diese Gedenkstunde hier im Plenarsaal oder an den Bildschirmen verfolgen.
(Beifall)
Dmitrij SchostakowitschStreichquartett Nr. 8 c-moll, op. 1102. Satz Allegro
Ausdruck aus dem Internet-Angebot des Deutschen Bundestages
https://www.bundestag.de/de/parlament/praesidium/reden/2014/001/261296
Stand: 25.09.2017
</rohtext>
</text>

<text person="Norbert Lammert" titel="Feierstunde des Deutschen Bundestages aus Anlass des 65. Jahrestages des Inkrafttretens des Grundgesetzes" datum="23. Mai 2014" ort="Berlin"  untertitel="" url="" anrede="">
<rohtext>
Guten Morgen, meine Damen und Herren!
Liebe Kolleginnen und Kollegen!
Sehr geehrter Herr Bundespräsident!
Frau Bundeskanzlerin!
Herr Vizepräsident des Bundesrates!
Herr Präsident des Bundesverfassungsgerichts! Exzellenzen!
Lieber Herr Kermani!
Verehrte Gäste! 
